# Generated by Django 4.0 on 2024-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username2',
            field=models.CharField(default=models.CharField(max_length=60), max_length=60),
        ),
    ]
