# Generated by Django 4.0 on 2024-04-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_username_alter_account_username2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username2',
            new_name='username',
        ),
    ]
