# Generated by Django 4.0 on 2024-04-17 19:01

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_username2_alter_account_username'),
    ]

    operations = [
	migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=models.CharField(max_length=60), max_length=60),
        ),
    ]
