# Generated by Django 4.0 on 2024-04-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
