# Generated by Django 4.0 on 2024-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=60, unique=True, verbose_name='email'), max_length=60),
        ),
    ]
