# Generated by Django 4.0 on 2024-04-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username2',
        ),
    ]
